services:
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=file:./dev.db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/prisma
